### ISSUE TITLE
Psyllid does not handle set_condition messages

### ISSUE THREAD

**Issue by nsoblath** [project8/psyllid#45]
`dripline::hub:: __do_handle_set_condition_request()` needs to be reimplemented in `request_receiver`.

**Comment by laroque** [comment]
proposal:
a configuration top-level key in the psyllid config file `set_condition_actions` which is a mapping of condition ID values onto batch-actions. In the event that a set_condition is received for which there is an entry, create a batch executor (configure the existing one?) and run it on the actions set.

**Comment by laroque** [comment]
Next update, for myself more than anything....
---
#### psyllid config file

The following should be valid in a psyllid config file:
```
on-startup:
    - some
    - list
    - at
    -startup
batch-commands:
    hard-abort:
        - steps
        - to
        - hard
        - abort
    soft-abort:
        - steps
        - to
        - soft
        - abort
    build-mask:
        - steps
        - to build the mask
```
---
#### Batch_executor
- Update to store a param_node of `batch-commands`. It starts with a default set coded into server_config and updates with the config file (upserting config file into defaults).
- Add a method to do_batch_command(<some_key>); which places the corresponding param_array of actions into the batch_executor queue.
- In some method (the constructor?), register commands to call the above method (each registered cmd has a different arg to the above specifying a name from the node)
---
#### server_config
update server config with the following initial content
```
batch-commands:
    hard-abort:
        - steps
        - to stop NOW
set-conditions:
    10: <valid-cmd-without-args>
    12: <another-such>
```
---
#### request_receiver
implement the set_condition handler override in request_receiver to properly decode the above param_node and call the corresponding top-level cmd
